/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Draft;

import java.awt.Color;

/**
 *
 * @author Tamal
 */
public class NewJFrame1 extends javax.swing.JFrame {

    Color defaultColor, clickedColor, defaultColor2;
    public NewJFrame1() {
        initComponents();
        defaultColor = new Color(167,190,174);
        clickedColor = new Color(35,78,112);
        //defaultColor2 = new Color(231,232,209);
        //System.out.println(clickedColor);
        
        //set color on runTime
        
        dashboard.setBackground(defaultColor);
        caseainformation.setBackground(defaultColor);
        criminalInformation.setBackground(defaultColor);
        courtInformation.setBackground(defaultColor);
        judgeInformation.setBackground(defaultColor);
        policeInformation.setBackground(defaultColor);
        prisonInformation.setBackground(defaultColor);
        ppInformation.setBackground(defaultColor);
        personalInformation.setBackground(defaultColor);
        editProfile.setBackground(defaultColor);
        addNewAdmin.setBackground(defaultColor);
        logOut.setBackground(defaultColor);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        caseainformation = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        criminalInformation = new javax.swing.JLabel();
        courtInformation = new javax.swing.JLabel();
        judgeInformation = new javax.swing.JLabel();
        policeInformation = new javax.swing.JLabel();
        prisonInformation = new javax.swing.JLabel();
        ppInformation = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        personalInformation = new javax.swing.JLabel();
        editProfile = new javax.swing.JLabel();
        addNewAdmin = new javax.swing.JLabel();
        logOut = new javax.swing.JLabel();
        navigationBar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        changablePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(231, 232, 209));

        jPanel2.setBackground(new java.awt.Color(35, 78, 112));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/government-5ac0cd4c8eadf2.8703488915225849085844.png"))); // NOI18N

        jTextField1.setBackground(new java.awt.Color(35, 78, 112));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(240, 240, 240));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Legal Case Management System");
        jTextField1.setBorder(null);

        jTextField2.setBackground(new java.awt.Color(35, 78, 112));
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(231, 232, 209));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("People's Republic of Bangladesh");
        jTextField2.setBorder(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logo-70-80.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                    .addComponent(jTextField2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(167, 190, 174));

        caseainformation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        caseainformation.setForeground(new java.awt.Color(240, 240, 240));
        caseainformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caseainformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/case-file-30.png"))); // NOI18N
        caseainformation.setText("Case Information");
        caseainformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseainformationMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                caseainformationMousePressed(evt);
            }
        });

        dashboard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dashboard.setForeground(new java.awt.Color(240, 240, 240));
        dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/dashboard-30.png"))); // NOI18N
        dashboard.setText("Dashboard");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashboardMousePressed(evt);
            }
        });

        criminalInformation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        criminalInformation.setForeground(new java.awt.Color(240, 240, 240));
        criminalInformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        criminalInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/criminal-30.png"))); // NOI18N
        criminalInformation.setText("Criminal Information");
        criminalInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criminalInformationMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                criminalInformationMousePressed(evt);
            }
        });

        courtInformation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        courtInformation.setForeground(new java.awt.Color(240, 240, 240));
        courtInformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        courtInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/court-30.png"))); // NOI18N
        courtInformation.setText("Court Information");
        courtInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courtInformationMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                courtInformationMousePressed(evt);
            }
        });

        judgeInformation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        judgeInformation.setForeground(new java.awt.Color(240, 240, 240));
        judgeInformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judgeInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/judge-30.png"))); // NOI18N
        judgeInformation.setText("Judge Information");
        judgeInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                judgeInformationMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                judgeInformationMousePressed(evt);
            }
        });

        policeInformation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        policeInformation.setForeground(new java.awt.Color(240, 240, 240));
        policeInformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        policeInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/police-30.png"))); // NOI18N
        policeInformation.setText("Police Information");
        policeInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                policeInformationMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                policeInformationMousePressed(evt);
            }
        });

        prisonInformation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prisonInformation.setForeground(new java.awt.Color(240, 240, 240));
        prisonInformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prisonInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/prison-30.png"))); // NOI18N
        prisonInformation.setText("Prison Information");
        prisonInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prisonInformationMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                prisonInformationMousePressed(evt);
            }
        });

        ppInformation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ppInformation.setForeground(new java.awt.Color(240, 240, 240));
        ppInformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ppInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pp-30.png"))); // NOI18N
        ppInformation.setText("Public Prosecutor");
        ppInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppInformationMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ppInformationMousePressed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(35, 78, 112));
        jLabel4.setText("Login As");

        jTextField3.setBackground(new java.awt.Color(167, 190, 174));
        jTextField3.setForeground(new java.awt.Color(231, 232, 209));
        jTextField3.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("My Data");

        personalInformation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        personalInformation.setForeground(new java.awt.Color(231, 232, 209));
        personalInformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personalInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/personal-information-20.png"))); // NOI18N
        personalInformation.setText("Personal Information");
        personalInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                personalInformationMousePressed(evt);
            }
        });

        editProfile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        editProfile.setForeground(new java.awt.Color(231, 232, 209));
        editProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/editing-20.png"))); // NOI18N
        editProfile.setText("Edit Profile");
        editProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editProfileMousePressed(evt);
            }
        });

        addNewAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addNewAdmin.setForeground(new java.awt.Color(231, 232, 209));
        addNewAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addNewAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/admin-settings-20.png"))); // NOI18N
        addNewAdmin.setText("Add New Admin");
        addNewAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addNewAdminMousePressed(evt);
            }
        });

        logOut.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        logOut.setForeground(new java.awt.Color(240, 240, 240));
        logOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logout-20.png"))); // NOI18N
        logOut.setText("Log Out");
        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logOutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personalInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prisonInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(policeInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(judgeInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courtInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criminalInformation)
                    .addComponent(caseainformation, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(caseainformation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(criminalInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(courtInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(judgeInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(policeInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prisonInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ppInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(personalInformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addNewAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        navigationBar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        navigationBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home-22-20.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(231, 232, 209));

        jLabel3.setBackground(new java.awt.Color(231, 232, 209));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search-20.png"))); // NOI18N

        jLabel5.setText("Search here ...");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menu-22-20.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout changablePanelLayout = new javax.swing.GroupLayout(changablePanel);
        changablePanel.setLayout(changablePanelLayout);
        changablePanelLayout.setHorizontalGroup(
            changablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        changablePanelLayout.setVerticalGroup(
            changablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(navigationBar, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(changablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navigationBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addComponent(changablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
       //tabbedPane.setSelectedIndex(0);
        InternalFrameDashboard dashboardFrame = new InternalFrameDashboard();
        changablePanel.removeAll();
        changablePanel.add(dashboardFrame).setVisible(true);
    }//GEN-LAST:event_dashboardMouseClicked

    private void caseainformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caseainformationMouseClicked
        //tabbedPane.setSelectedIndex(1);
        InternalFrameCaseInfo caseInfoFrame = new InternalFrameCaseInfo();
        changablePanel.removeAll();
        changablePanel.add(caseInfoFrame).setVisible(true);
    }//GEN-LAST:event_caseainformationMouseClicked

    private void criminalInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criminalInformationMouseClicked
        //tabbedPane.setSelectedIndex(2);
        InternalFrameCriminalInfo criminalInfoFrame = new InternalFrameCriminalInfo();
        changablePanel.removeAll();
        changablePanel.add(criminalInfoFrame).setVisible(true);
    }//GEN-LAST:event_criminalInformationMouseClicked

    private void courtInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courtInformationMouseClicked
        //tabbedPane.setSelectedIndex(3);
        InternalFrameCourtInfo courtInfoFrame = new InternalFrameCourtInfo();
        changablePanel.removeAll();
        changablePanel.add(courtInfoFrame).setVisible(true);
    }//GEN-LAST:event_courtInformationMouseClicked

    private void judgeInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_judgeInformationMouseClicked
        //tabbedPane.setSelectedIndex(4);
        InternalFrameJudgeInfo judgeInfoFrame = new InternalFrameJudgeInfo();
        changablePanel.removeAll();
        changablePanel.add(judgeInfoFrame).setVisible(true);
    }//GEN-LAST:event_judgeInformationMouseClicked

    private void policeInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_policeInformationMouseClicked
        //tabbedPane.setSelectedIndex(5);
        InternalFramePoliceInfo policeInfoFrame = new InternalFramePoliceInfo();
        changablePanel.removeAll();
        changablePanel.add(policeInfoFrame).setVisible(true);
    }//GEN-LAST:event_policeInformationMouseClicked

    private void prisonInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prisonInformationMouseClicked
        //tabbedPane.setSelectedIndex(6);
        InternalFramePrisonInfo prisonInfoFrame = new InternalFramePrisonInfo();
        changablePanel.removeAll();
        changablePanel.add(prisonInfoFrame).setVisible(true);
    }//GEN-LAST:event_prisonInformationMouseClicked

    private void ppInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppInformationMouseClicked
        //tabbedPane.setSelectedIndex(7);
        InternalFramePPInfo ppInfoFrame = new InternalFramePPInfo();
        changablePanel.removeAll();
        changablePanel.add(ppInfoFrame).setVisible(true);
    }//GEN-LAST:event_ppInformationMouseClicked

    private void dashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMousePressed
        // TODO add your handling code here:
        dashboard.setBackground(clickedColor);
        dashboard.setOpaque(true);
        caseainformation.setBackground(defaultColor);
        criminalInformation.setBackground(defaultColor);
        courtInformation.setBackground(defaultColor);
        judgeInformation.setBackground(defaultColor);
        policeInformation.setBackground(defaultColor);
        prisonInformation.setBackground(defaultColor);
        ppInformation.setBackground(defaultColor);
        personalInformation.setBackground(defaultColor2);
        editProfile.setBackground(defaultColor2);
        addNewAdmin.setBackground(defaultColor2);
        logOut.setBackground(defaultColor);
        
        navigationBar.setText("> Dashboard");
    }//GEN-LAST:event_dashboardMousePressed

    private void caseainformationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caseainformationMousePressed
        // TODO add your handling code here:
        dashboard.setBackground(defaultColor);
        caseainformation.setBackground(clickedColor);
        caseainformation.setOpaque(true);
        criminalInformation.setBackground(defaultColor);
        courtInformation.setBackground(defaultColor);
        judgeInformation.setBackground(defaultColor);
        policeInformation.setBackground(defaultColor);
        prisonInformation.setBackground(defaultColor);
        ppInformation.setBackground(defaultColor);
        personalInformation.setBackground(defaultColor2);
        editProfile.setBackground(defaultColor2);
        addNewAdmin.setBackground(defaultColor2);
        logOut.setBackground(defaultColor);
        
        navigationBar.setText("> Case Information");
    }//GEN-LAST:event_caseainformationMousePressed

    private void criminalInformationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criminalInformationMousePressed
        // TODO add your handling code here:
        dashboard.setBackground(defaultColor);
        caseainformation.setBackground(defaultColor);
        criminalInformation.setBackground(clickedColor);
        criminalInformation.setOpaque(true);
        courtInformation.setBackground(defaultColor);
        judgeInformation.setBackground(defaultColor);
        policeInformation.setBackground(defaultColor);
        prisonInformation.setBackground(defaultColor);
        ppInformation.setBackground(defaultColor);
        personalInformation.setBackground(defaultColor);
        editProfile.setBackground(defaultColor);
        addNewAdmin.setBackground(defaultColor);
        logOut.setBackground(defaultColor);
        
        navigationBar.setText("> Criminal Information");
    }//GEN-LAST:event_criminalInformationMousePressed

    private void courtInformationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courtInformationMousePressed
        // TODO add your handling code here:
        dashboard.setBackground(defaultColor);
        caseainformation.setBackground(defaultColor);
        criminalInformation.setBackground(defaultColor);
        courtInformation.setBackground(clickedColor);
        courtInformation.setOpaque(true);
        judgeInformation.setBackground(defaultColor);
        policeInformation.setBackground(defaultColor);
        prisonInformation.setBackground(defaultColor);
        ppInformation.setBackground(defaultColor);
        personalInformation.setBackground(defaultColor);
        editProfile.setBackground(defaultColor);
        addNewAdmin.setBackground(defaultColor);
        logOut.setBackground(defaultColor);
        
        navigationBar.setText("> Court Information");
    }//GEN-LAST:event_courtInformationMousePressed

    private void judgeInformationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_judgeInformationMousePressed
        // TODO add your handling code here:
        dashboard.setBackground(defaultColor);
        caseainformation.setBackground(defaultColor);
        criminalInformation.setBackground(defaultColor);
        courtInformation.setBackground(defaultColor);
        judgeInformation.setBackground(clickedColor);
        judgeInformation.setOpaque(true);
        policeInformation.setBackground(defaultColor);
        prisonInformation.setBackground(defaultColor);
        ppInformation.setBackground(defaultColor);
        personalInformation.setBackground(defaultColor);
        editProfile.setBackground(defaultColor);
        addNewAdmin.setBackground(defaultColor);
        logOut.setBackground(defaultColor);
        
        navigationBar.setText("> Judge Information");
    }//GEN-LAST:event_judgeInformationMousePressed

    private void policeInformationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_policeInformationMousePressed
        // TODO add your handling code here:
        dashboard.setBackground(defaultColor);
        caseainformation.setBackground(defaultColor);
        criminalInformation.setBackground(defaultColor);
        courtInformation.setBackground(defaultColor);
        judgeInformation.setBackground(defaultColor);
        policeInformation.setBackground(clickedColor);
        policeInformation.setOpaque(true);
        prisonInformation.setBackground(defaultColor);
        ppInformation.setBackground(defaultColor);
        personalInformation.setBackground(defaultColor2);
        editProfile.setBackground(defaultColor2);
        addNewAdmin.setBackground(defaultColor2);
        logOut.setBackground(defaultColor);
        
        navigationBar.setText("> Police Information");
    }//GEN-LAST:event_policeInformationMousePressed

    private void prisonInformationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prisonInformationMousePressed
        // TODO add your handling code here:
        dashboard.setBackground(defaultColor);
        caseainformation.setBackground(defaultColor);
        criminalInformation.setBackground(defaultColor);
        courtInformation.setBackground(defaultColor);
        judgeInformation.setBackground(defaultColor);
        policeInformation.setBackground(defaultColor);
        prisonInformation.setBackground(clickedColor);
        prisonInformation.setOpaque(true);
        ppInformation.setBackground(defaultColor);
        personalInformation.setBackground(defaultColor);
        editProfile.setBackground(defaultColor);
        addNewAdmin.setBackground(defaultColor);
        logOut.setBackground(defaultColor);
        
        navigationBar.setText("> Prison Information");
    }//GEN-LAST:event_prisonInformationMousePressed

    private void ppInformationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppInformationMousePressed
        // TODO add your handling code here:
        dashboard.setBackground(defaultColor);
        caseainformation.setBackground(defaultColor);
        criminalInformation.setBackground(defaultColor);
        courtInformation.setBackground(defaultColor);
        judgeInformation.setBackground(defaultColor);
        policeInformation.setBackground(defaultColor);
        prisonInformation.setBackground(defaultColor);
        ppInformation.setBackground(clickedColor);
        ppInformation.setOpaque(true);
        personalInformation.setBackground(defaultColor);
        editProfile.setBackground(defaultColor);
        addNewAdmin.setBackground(defaultColor);
        logOut.setBackground(defaultColor);
        
        navigationBar.setText("> Attorney Information");
    }//GEN-LAST:event_ppInformationMousePressed

    private void personalInformationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personalInformationMousePressed
        // TODO add your handling code here:
        dashboard.setBackground(defaultColor);
        caseainformation.setBackground(defaultColor);
        criminalInformation.setBackground(defaultColor);
        courtInformation.setBackground(defaultColor);
        judgeInformation.setBackground(defaultColor);
        policeInformation.setBackground(defaultColor);
        prisonInformation.setBackground(defaultColor);
        ppInformation.setBackground(defaultColor);
        personalInformation.setBackground(clickedColor);
        personalInformation.setOpaque(true);
        editProfile.setBackground(defaultColor);
        addNewAdmin.setBackground(defaultColor);
        logOut.setBackground(defaultColor);
        
        navigationBar.setText("> Personal Information");
    }//GEN-LAST:event_personalInformationMousePressed

    private void editProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMousePressed
        // TODO add your handling code here:
        dashboard.setBackground(defaultColor);
        caseainformation.setBackground(defaultColor);
        criminalInformation.setBackground(defaultColor);
        courtInformation.setBackground(defaultColor);
        judgeInformation.setBackground(defaultColor);
        policeInformation.setBackground(defaultColor);
        prisonInformation.setBackground(defaultColor);
        ppInformation.setBackground(defaultColor);
        personalInformation.setBackground(defaultColor);
        editProfile.setBackground(clickedColor);
        editProfile.setOpaque(true);
        addNewAdmin.setBackground(defaultColor);
        logOut.setBackground(defaultColor);
        
        navigationBar.setText("> Edit Your Profile");
    }//GEN-LAST:event_editProfileMousePressed

    private void addNewAdminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewAdminMousePressed
        // TODO add your handling code here:
        dashboard.setBackground(defaultColor);
        caseainformation.setBackground(defaultColor);
        criminalInformation.setBackground(defaultColor);
        courtInformation.setBackground(defaultColor);
        judgeInformation.setBackground(defaultColor);
        policeInformation.setBackground(defaultColor);
        prisonInformation.setBackground(defaultColor);
        ppInformation.setBackground(defaultColor);
        personalInformation.setBackground(defaultColor);
        editProfile.setBackground(defaultColor);
        addNewAdmin.setBackground(clickedColor);
        addNewAdmin.setOpaque(true);
        logOut.setBackground(defaultColor);
        
        navigationBar.setText("> Add Admin");
    }//GEN-LAST:event_addNewAdminMousePressed

    private void logOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMousePressed
        // TODO add your handling code here:
        dashboard.setBackground(defaultColor);
        caseainformation.setBackground(defaultColor);
        criminalInformation.setBackground(defaultColor);
        courtInformation.setBackground(defaultColor);
        judgeInformation.setBackground(defaultColor);
        policeInformation.setBackground(defaultColor);
        prisonInformation.setBackground(defaultColor);
        ppInformation.setBackground(defaultColor);
        personalInformation.setBackground(defaultColor);
        editProfile.setBackground(defaultColor);
        addNewAdmin.setBackground(defaultColor);
        logOut.setBackground(clickedColor);
        logOut.setOpaque(true);
        
        navigationBar.setText("> Log Out");
    }//GEN-LAST:event_logOutMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addNewAdmin;
    private javax.swing.JLabel caseainformation;
    private javax.swing.JPanel changablePanel;
    private javax.swing.JLabel courtInformation;
    private javax.swing.JLabel criminalInformation;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel editProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel judgeInformation;
    private javax.swing.JLabel logOut;
    private javax.swing.JLabel navigationBar;
    private javax.swing.JLabel personalInformation;
    private javax.swing.JLabel policeInformation;
    private javax.swing.JLabel ppInformation;
    private javax.swing.JLabel prisonInformation;
    // End of variables declaration//GEN-END:variables
}
